import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <h2 className="text-3xl flex items-center justify-center font-extrabold underline
      ">Log-in Form</h2>
      <body className={`${inter.className} bg-white`}>{children}</body>
    </html>
  );
}
